name: secrets

on: [pull]

env: 
  FLIGHT_API: ${{ secrets.FLIGHT_API }}
  SHEETY_BEARER: ${{ secrets.SHEETY_BEARER }}
  TWILIO_SID: ${{ secrets.TWILIO_SID }}
  FTWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
